[tool.poetry]
name = "cg-bundler"
version = "0.1.0"
description = ""
authors = ["Daniel Trowbridge <blujupiter32@pm.me>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
